name: Build and Upload Wheel on Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Add Dynamic Versioning Plugin
        run: poetry self add poetry-dynamic-versioning[plugin]

      - name: Build package
        run: poetry build -f wheel

      - name: Upload wheel to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl

      - name: Publish package to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
